apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: edgeroutes.swacd.io
spec:
  group: swacd.io
  scope: Namespaced
  names:
    kind: EdgeRoute
    plural: edgeroutes
    singular: edgeroute
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                fqdn:
                  type: string
                hostnames:
                  type: array
                  items:
                    type: string
                routes:
                  type: array
                  items:
                    type: object
                    properties:
                      path:
                        type: string
                      backendRef:
                        type: object
                        properties:
                          apiVersion: { type: string }
                          kind: { type: string }
                          name: { type: string }
                      cache:
                        type: object
                        properties:
                          enabled:
                            type: boolean
                          ttl:
                            type: integer
                authentication:
                  type: array
                  items:
                    type: object
                    properties:
                      type: { type: string }
                      certificateRef:
                        type: object
                        properties:
                          name: { type: string }
                policies:
                  type: array
                  items:
                    type: object
                    properties:
                      wafPolicyRef:
                        type: string
            status:
              type: object
              properties:
                phase: { type: string }
                message: { type: string }
