apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cloudflareproviders.providers.swacd.io
spec:
  group: providers.swacd.io
  scope: Namespaced
  names:
    kind: CloudflareProvider
    plural: cloudflareproviders
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                accountId: { type: string }
                apiTokenSecretRef:
                  type: object
                  properties:
                    name: { type: string }
                zone: { type: string }
                email: { type: string }
            status:
              type: object
              properties:
                phase: { type: string }
                message: { type: string }
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: akamaiproviders.providers.swacd.io
spec:
  group: providers.swacd.io
  scope: Namespaced
  names:
    kind: AkamaiProvider
    plural: akamaiproviders
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                contractId: { type: string }
                clientSecretRef:
                  type: object
                  properties:
                    name: { type: string }
            status:
              type: object
              properties:
                phase: { type: string }
                message: { type: string }
