apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenants.swacd.io
spec:
  group: swacd.io
  scope: Namespaced
  names:
    kind: Tenant
    plural: tenants
    singular: tenant
    shortNames:
      - tnt
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tenantId:
                  type: string
                ownerEmail:
                  type: string
                lob:
                  type: string
                description:
                  type: string
                edgeServiceProviders:
                  type: array
                  items:
                    type: object
                    properties:
                      apiVersion:
                        type: string
                      kind:
                        type: string
                      name:
                        type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      message:
                        type: string
